---
abstract: 'FIDO/U2F Authentication Test Client'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires:
  Authen::U2F: '0'
  Crypt::Misc: '0'
  File::Slurp: '0'
  Path::Tiny: '0'
  Test::Exception: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Authen-U2F-Tester
requires:
  Carp: '0'
  Crypt::OpenSSL::X509: '0'
  Crypt::PK::ECC: '0'
  Digest::SHA: '0'
  Exporter: '0'
  JSON::MaybeXS: '0'
  List::Util: '0'
  MIME::Base64: '0'
  Moose: '0'
  Moose::Role: '0'
  MooseX::AttributeShortcuts: '0'
  MooseX::SingleArg: '0'
  base: '0'
  constant: '0'
  namespace::autoclean: '0'
  perl: '5.006'
  strictures: '2'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Authen-U2F-Tester
  homepage: http://search.cpan.org/dist/Authen-U2F-Tester/
  repository: git://github.com/mschout/perl-authen-u2f-tester.git
version: '0.02'
x_serialization_backend: 'YAML::Tiny version 1.69'
