---
abstract: 'FIDO/U2F Authentication Test Client'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires:
  Authen::U2F: '0'
  Crypt::Misc: '0'
  File::Slurp: '0'
  Path::Tiny: '0'
  Test::Exception: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Authen-U2F-Tester
provides:
  Authen::U2F::Tester:
    file: lib/Authen/U2F/Tester.pm
    version: '0.01'
  Authen::U2F::Tester::Const:
    file: lib/Authen/U2F/Tester/Const.pm
    version: '0.01'
  Authen::U2F::Tester::Error:
    file: lib/Authen/U2F/Tester/Error.pm
    version: '0.01'
  Authen::U2F::Tester::Keypair:
    file: lib/Authen/U2F/Tester/Keypair.pm
    version: '0.01'
  Authen::U2F::Tester::RegisterResponse:
    file: lib/Authen/U2F/Tester/RegisterResponse.pm
    version: '0.01'
  Authen::U2F::Tester::Role::Response:
    file: lib/Authen/U2F/Tester/Role/Response.pm
    version: '0.01'
  Authen::U2F::Tester::SignResponse:
    file: lib/Authen/U2F/Tester/SignResponse.pm
    version: '0.01'
requires:
  Crypt::OpenSSL::X509: '0'
  Crypt::PK::ECC: '0'
  Digest::SHA: '0'
  Exporter: '0'
  JSON::MaybeXS: '0'
  List::Util: '0'
  MIME::Base64: '0'
  Moose: '0'
  Moose::Role: '0'
  MooseX::AttributeShortcuts: '0'
  MooseX::SingleArg: '0'
  base: '0'
  constant: '0'
  namespace::autoclean: '0'
  perl: '5.006'
  strictures: '2'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Authen-U2F-Tester
  homepage: http://search.cpan.org/dist/Authen-U2F-Tester/
  repository: git://github.com/mschout/perl-authen-u2f-tester.git
version: '0.01'
x_serialization_backend: 'YAML::Tiny version 1.70'
